version: '3.8'
services:
  mysql_server:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=plataforma_tcc_2024
      - MYSQL_DATABASE=client_data
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql-scripts-client:/docker-entrypoint-initdb.d
    networks:
      - backend

  postgres_server:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=plataforma_tcc_2024
      - POSTGRES_DB=product_data
      - POSTGRES_INITDB_SCRIPTS_PATH=/docker-entrypoint-initdb.d-product
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql-scripts-product:/docker-entrypoint-initdb.d-product
    networks:
      - backend

networks:
  backend:

volumes:
  mysql_data:
  postgres_data:

